# Generated by Django 3.2.8 on 2024-05-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id_negocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_negocio', models.CharField(max_length=50, verbose_name='Nombre del Negocio')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('numero_de_local', models.CharField(max_length=50, verbose_name='Número de Local')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('Id_negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jigxxer.negocio', verbose_name='Id_negocio')),
            ],
        ),
    ]
