# Generated by Django 5.0.6 on 2024-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigxxer', '0002_negocio_usuario_administrador_venta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='categoria',
            field=models.CharField(default=1, max_length=1000, verbose_name='categoria'),
            preserve_default=False,
        ),
    ]
